---
- name: Check OS dependencies
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Display OS version
      ansible.builtin.debug:
        msg: "Hostname: {{ ansible_hostname }}, IP: {{ ansible_host }}, OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
